---
- hosts: all
  become: true
  vars:
    users:
    - "krishnar"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      state: "present"
      createhome: yes
      shell: /bin/bash
      groups: wheel
    with_items: "{{ users }}"

  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'pub_keys/'+ item + '.pub') }}"
    with_items: "{{ users }}"

...
