---
- hosts: all
  become: true
  vars:
    users:
    - "krishnar"

  tasks:
  - name: Remove the user
    user:
      name: "{{ item }}"
      state: absent
      remove: yes
    with_items: "{{ users }}"
... 
